### ISSUE TITLE
multiple definitions of main

### ISSUE THREAD

**Issue by brayeofsunshine** [sahrk/DGGRID#1]
I recently downloaded version 7.0 from here, and am running into some issues running the makefile for the dggrid command. When I run the make command, I get the error "multiple definition of 'main'" and then undefined reference errors for all the other files. I am using a conda environment and used conda install for the gdal files, am unsure if that could be causing any issues. Any help is appreciated!

**Comment by sahrk** [comment]
@brayeofsunshine can you post or email the complete output from `make`? Please do `make clean; make &> make.out` and send me the `make.out` file.
