### ISSUE TITLE
GDAL compile issue on other environments like nodejs

### ISSUE THREAD

**Issue by am2222** [sahrk/DGGRID#17]
Hi,
Is there any possible way to make GDAL requirement to compile the code optionally? I am trying to make a wrapper for nodejs and the issue is with linking GDAL to the library to compile (https://github.com/am2222/dggridjs), currently I am using previous version of dggrid library which does not have any linkage to GDAL.On the windows also there are lots of issues with compiling GDAL and linking it (however I could manage to do it). 
I was thinking about the potential way to make this part optional to be able to easily port it for other environments as well.

**Comment by sahrk** [comment]
Yes, I already have a version that does that. I will merge those changes.

**Comment by am2222** [comment]
@sahrk that would be great. Thanks you

**Comment by sahrk** [comment]
I just pushed version 7.1, which allows DGGRID to be built without GDAL by setting `BUILD_WITH_GDAL = FALSE` in `src/MakeIncludes.noCMake`. Sorry it's taken so long!

**Comment by am2222** [comment]
@sahrk thanks, I really appreciate it. I guess now I can compile the nodejs wrapper with no issue. 
Thanks
