### ISSUE TITLE
GEOJSON output format question

### ISSUE THREAD

**Issue by mezcalhead** [sahrk/DGGRID#2]
I noticed the GEOJSON output doesn't have any newline breaks.  Question: just for a little readability when scanning raw GEOJSON outputs, can we add a newline break between records?   This assumes there's no impact to the GEOJSON interoperability.

**Comment by sahrk** [comment]
There are actually two GEOJSON output paths. The older path (e.g., see
DGGRID/examples/gridgenGeoJSON) is our code, and that looks like the one
with no line breaks; I will fix that. But note that there is a newer path
using GDAL (e.g., see DGGRID/examples/planetRiskGridGen) that does have
line breaks.

**Comment by sahrk** [comment]
There are now newlines after features in the output files produced when using `GEOJSON` for parameter `cell_output_type` or `point_output_type`.
