### ISSUE TITLE
Compiling on windows

### ISSUE THREAD

**Issue by am2222** [sahrk/DGGRID#3]
Hi,
I am working of a python wrapper (https://github.com/am2222/pydggrid) of this library and tried to compile it on windows. there are some errors with abstract functions. I had to change some of them to be able to compile them using `MSVC`, However I did not check them to see if those changes breaks the functionality of the classes or not, I wanted to share them here to see if it is possible to fix them for future versions to be able to compile this library on windows without such changes

https://github.com/am2222/pydggrid/blob/d7a0bdd3bd080cef225a376f986db029936ce69d/src/lib/DgOutLocTextFile.h#L62

https://github.com/am2222/pydggrid/blob/d7a0bdd3bd080cef225a376f986db029936ce69d/src/lib/DgOutLocFile.h#L84

There are some other changes which I will provide them here soon.

**Comment by sahrk** [comment]
While changing those methods so that they are not pure virtual shouldn't change the program behavior, I am surprised that `MVSC` can't handle them. Would you be willing to share the compiler errors you get from those lines?

**Comment by am2222** [comment]
@sahrk thanks for the reply. Yes sure I will start to build it on windows and share the error messages.  I guess by fixing these error it would also be possible to build it on vcpkg so we can use it as a library and it is easier to write wrappers for python or nodejs

**Comment by am2222** [comment]
@sahrk for some reason I changed those lines back to the pure abstract functions and code compiled well now , I will close this issues now. Also sorry for my late update on this issues. 
https://github.com/am2222/pydggrid/blob/2c9dfc5f49d8b81eadaf709e7e8d2f2cdc976046/src/lib/DgOutLocFile.h#L100

https://github.com/am2222/pydggrid/blob/2c9dfc5f49d8b81eadaf709e7e8d2f2cdc976046/src/lib/DgOutLocTextFile.h#L64
