### ISSUE TITLE
Dual License?

### ISSUE THREAD

**Issue by mxplusb** [sahrk/DGGRID#31]
Is there an opportunity for this project to be dual licensed with something like a BSD-2 or BSD-3 license? I want to use this library with an Unreal Engine project I'm working on, but the copyleft restrictions are incompatible with the Unreal Engine project so I can't use it.

**Comment by sahrk** [comment]
Sorry it took so long to reply, I needed to look into this a bit. My intent in choosing the GPL was to make DGGRID as open as possible specifically for non-commercial use. A more commercially permissive license would obviate some of that. So at least for now I don't want to change the license. I note that Stallman suggests "license exceptions" for situations like yours. If that interests you then please contact me directly at sahrk@sou.edu.
