### ISSUE TITLE
Meta settings for SMOS grid

### ISSUE THREAD

**Issue by sebhahn** [sahrk/DGGRID#5]
Hi, I would like to reproduce the SMOS grid. What would be the settings for the meta file? Would it be also possible to use a predefined distance (in km) between grid points to generate a similar grid with a larger or smaller grid point distance?

**Comment by sahrk** [comment]
The SMOS grid is an ISEA4H resolution 9, which would be meta-file parameters:

    dggs_type ISEA4H
    dggs_res_spec 9

You could generate other ISEA4H resolutions to get different intercell spacings by changing the `dggs_res_spec` parameter. See the ISEA4H table in Appendix D (page 30) of the **DGGRID** version 7.0 manual. 

I should mention that there are metafile parameters that tell **DGGRID** to approximate an input intercell spacing, but that code needs to be updated to reflect the actual intercell spacings given in Appendix D of the manual (which were empirically derived). For now I recommend using the tables and manually choosing a resolution.

**Comment by sebhahn** [comment]
Thanks! Do I need to define the origin as well or is it the default one (11.25, 58.28)?

**Comment by sahrk** [comment]
@sebhahn I'm pretty certain it is the default orientation (the SMOS documentation just says "ISEA4H9").

**Comment by sebhahn** [comment]
Yes, that's exactly I wanted to know: "interprets the generated lat/lon coordinates as being on a WGS84 ellipsoid" even though the coordinates are computed on a projected spherical earth. 

Sorry for the confusion, I meant ellipsoid. 

The distances (i.e. CLS) from the statistics are computed for the projected coordinates, right? In order to get similar statistics for the points assumed on an "ellipsoid" the Earth's curvature needs to be taken into account when computing the geodesic distance.

**Comment by sahrk** [comment]
All areas and distances are computed on the sphere. They would be slightly different if measured on the ellipsoid.

**Comment by sebhahn** [comment]
@sahrk thanks a lot for your help!
