### ISSUE TITLE
ISEA or FULLER 4D and 4T clipping dropouts?

### ISSUE THREAD

**Issue by allixender** [sahrk/DGGRID#58]
In the latest version, tested with v7.7 after (commit 1f2a38b2cd246df7d8841946c1b1daf3f40fa299)  ISEA4D and FULLER4D clipping produces interleaved output.

![image](https://user-images.githubusercontent.com/4483885/224285456-e4498964-8042-4903-9cb7-8a9e60d9e1f8.png)

```
dggrid_operation GENERATE_GRID
dggs_type ISEA4D
dggs_res_spec 8
clip_subset_type GDAL
clip_region_files temp_clip_france_coast.geojson
cell_output_type GDAL
cell_output_gdal_format GeoJSON
cell_output_file_name ISEA4D_8_test1.geojson
```

file: temp_clip_france_coast.geojson
```json
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 1 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 1.303658723831177, 49.269447326660156 ], [ 1.303658723831177, 50.061737060546875 ], [ -1.453048825263977, 50.061737060546875 ], [ -1.453048825263977, 49.269447326660156 ], [ 1.303658723831177, 49.269447326660156 ] ] ] } }
]
}
```

Similar with ISEA4T, but not hexagonal topologies.

But I am not sure how much earlier it was introduced.

Global (WHOLE_EARTH) doesn't produce these dropouts.

Changing clipper_scale_factor to low (1000) or higher (100000000) doesn't seem to have an effect.

**Comment by sahrk** [comment]
I found the bug, which I think I introduced in the big refactoring of version 7. But 4H and 4T grids should now work correctly. Please let me know if you find cases that still don't work.

**Comment by sahrk** [comment]
@allixender I'm going to close this, but let me know if you see any other problems.
