### ISSUE TITLE
Add -h and -v commandline flags 

### ISSUE THREAD

**Issue by allixender** [sahrk/DGGRID#60]
It would be great to have a simple starter flag `-v` for dggrid that shows the current compiled version, like so:

```shell
dggrid -v

#> DGGRID version 7.7 released December 8, 2022
# or dev version
#> DGGRID version 7.7-c75453454
```
Preferably that info conveys a release version number, or a "dev-commit" type version.

For completeness, a `-h` help flag would be nice with minimal info, such as:

```shell
dggrid -h

#> 
#> DGGRID version 7.7 released December 8, 2022
#> How to use:
#> 
#> dggrid metafile
#> 
#> dggrid -v
#> dggrid -h
#>
#> Credits:
#> Southern Terra Cognita Laboratory
#> website: http://www.discreteglobalgrids.org/
#> Kevin Sahr, https://inside.sou.edu/cs/kevinsahr.html, Director
#> 
#> License: GNU Affero General Public License v3.0
#>
#> Github development:
#> https://github.com/sahrk/DGGRID
```

**Comment by sahrk** [comment]
@allixender these flags have now been implemented. Please give them a try and let me know if you encounter any difficulties.
