### ISSUE TITLE
Question rather than issue - triangular grids 

### ISSUE THREAD

**Issue by space-beaver** [sahrk/DGGRID#61]
Many thanks for this very useful software. I would like to create a 10km triangular grid over scotland and I've been following the tutorial exaple of creating a hexagonal grid over SA. Is there a function in dggridR that can create a triangular grid? 

cheers
melissa

**Comment by sahrk** [comment]
> Many thanks for this very useful software. 

Thank you @space-beaver. 

>I would like to create a 10km triangular grid over scotland and I've been following the tutorial exaple of creating a hexagonal grid over SA. Is there a function in dggridR that can create a triangular grid?
> 
> cheers melissa

I'm not sure, because I am not myself an R/dggridR user. But @r-barnes would you be willing to answer this question?
