### ISSUE TITLE
cell.geojson doesnt have geometry

### ISSUE THREAD

**Issue by ChaudhuriC** [sahrk/DGGRID#63]
Dear Prof. Sahr,
   Hope you are doing well!

We are trying to incorporate aperture 3 DGGS into our current workflow of querying hazard data from a sql database using our IDEAS datamodel (https://www.sciencedirect.com/science/article/pii/S0924271620300502). We ran some tests with the DGGRID ISEA3H and it seems the geometry information is not getting created when I am opting for a gdal based output, be it geojson or kml. The binding with gdal went fine during installation though. I checked for coarse resolution DGGS, and the output as shapefile is coming fine. Unfortunately, for fine resolution (30m-1m)  shapefile is not really an option.

I am still not sure if it is binding with gdal that is creating problem or not. Can you please confirm if the cell.geojson has the consistent polygon attribute? Also, please let me know if there is a way to split the output files by no. of cells in case of too much data.

With regards,
Chiranjib

**Comment by sahrk** [comment]
> Dear Prof. Sahr, Hope you are doing well!

Thanks @ChaudhuriC, I hope you are also doing well!

> 
> We are trying to incorporate aperture 3 DGGS into our current workflow of querying hazard data from a sql database using our IDEAS datamodel (https://www.sciencedirect.com/science/article/pii/S0924271620300502). We ran some tests with the DGGRID ISEA3H and it seems the geometry information is not getting created when I am opting for a gdal based output, be it geojson or kml. The binding with gdal went fine during installation though. I checked for coarse resolution DGGS, and the output as shapefile is coming fine. Unfortunately, for fine resolution (30m-1m) shapefile is not really an option.
> I am still not sure if it is binding with gdal that is creating problem or not. Can you please confirm if the cell.geojson has the consistent polygon attribute? 

See the example `gridgenGeoJSON` (in the `examples` directory), which I believe does what you are asking. If you post the meta file you are using I will take a look and see if I can identify what is happening.

> Also, please let me know if there is a way to split the output files by no. of cells in case of too much data.

Yes, in your meta file set the parameter `max_cells_per_output_file` to the number of cells you want each output file to contain.

**Comment by ChaudhuriC** [comment]
Dear Prof. Sahr,
Thank you for your reply. 

Here is the metafile that I have used,

################################################################################
#
# gridgenGeoJSON.meta - example of a DGGRID metafile that generates a high 
#     resolution grid for testing using a mixed aperture ISEA
#     projection and clipped to a small area in Corvallis, Oregon. The output
#     grid is in GeoJSON format.
#
# Matt Gregory, 11/4/13
#
################################################################################

# specify the operation
dggrid_operation GENERATE_GRID

# specify the DGG
dggs_type ISEA3H
dggs_res_spec 6

# control the generation
clip_subset_type WHOLE_EARTH
geodetic_densify 0.0

# specify the output using GDAL-supported file formats
cell_output_type GDAL
cell_output_gdal_format GeoJSON
cell_output_file_name outputfiles/cells.geojson
point_output_type TEXT
point_output_file_name outputfiles/points.geojson
neighbor_output_type TEXT
neighbor_output_file_name outputfiles/neighbors
children_output_type TEXT
children_output_file_name outputfiles/children
densification 0
precision 6

#############################################################################
All other files except the cells.geojson are fine. Here is a couple of lines from the output cells.geojson;

{
"type": "FeatureCollection",
"name": "outputfiles\/cells.geojson",
"features": [
{ "type": "Feature", "properties": { "name": "1" }, "geometry": { "type": "Polygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "name": "2" }, "geometry": { "type": "Polygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "name": "3" }, "geometry": { "type": "Polygon", "coordinates": [ ] } },
{ "type": "Feature", "properties": { "name": "4" }, "geometry": { "type": "Polygon", "coordinates": [ ] } },

############################################################################
I modified the meta file in the gridgenGeoJson to create this one. However, the polygon slot is coming empty in the output file.

With regards,
Chiranjib

**Comment by sahrk** [comment]
@ChaudhuriC I ran your metafile and the `cells.geojson` file I generated looks correct:
~~~
{
"type": "FeatureCollection",
"name": "outputfiles\/cells.geojson",
"features": [
{ "type": "Feature", "properties": { "name": "1" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 8.691518028619617, 57.813979366835376 ], [ 11.25, 56.849892337399318 ], [ 13.808481967251572, 57.813979366202446 ], [ 12.905828551025154, 59.431156112258194 ], [ 9.594171453292679, 59.43115611161371 ], [ 8.691518028619617, 57.813979366835376 ] ] ] } },
etc.
~~~

So I am uncertain what is occurring. If possible, could you run your metafile again and this time redirect the `dggrid` output to a text file and give me that text file? e.g. `dggrid metafile.meta &> output.txt`

**Comment by ChaudhuriC** [comment]
Sure, here is the output.txt file 
###################################################
** executing DGGRID version 7.7 **
type sizes: big int: 64 bits / big double: 128 bits

** loading meta file gridgenGeoJSON.meta...
* using parameter values:
dggrid_operation GENERATE_GRID (user set)
dggs_type ISEA3H (user set)
dggs_topology HEXAGON (user set)
dggs_proj ISEA (user set)
dggs_aperture_type PURE (user set)
dggs_aperture 3 (user set)
proj_datum WGS84_AUTHALIC_SPHERE (default)
dggs_orient_specify_type SPECIFIED (user set)
dggs_num_placements 1 (user set)
dggs_orient_output_file_name grid.meta (default)
dggs_vert0_lon 11.25 (user set)
dggs_vert0_lat 58.2825 (user set)
dggs_vert0_azimuth 0 (user set)
dggs_res_specify_type SPECIFIED (user set)
dggs_res_spec 6 (user set)
rng_type RAND (default)
geodetic_densify 0 (user set)
clip_subset_type WHOLE_EARTH (user set)
clip_cell_seqnums  (default)
clip_cell_res 1 (default)
clip_cell_densification 1 (default)
clip_region_files test.gen (default)
clip_type POLY_INTERSECT (default)
clipper_scale_factor 1000000 (default)
densification 0 (user set)
longitude_wrap_mode WRAP (default)
unwrap_points true (default)
precision 6 (user set)
output_cell_label_type GLOBAL_SEQUENCE (default)
cell_output_type GDAL (user set)
point_output_type TEXT (user set)
randpts_output_type NONE (default)
cell_output_gdal_format GeoJSON (user set)
point_output_gdal_format GeoJSON (default)
collection_output_gdal_format GeoJSON (default)
clip_using_holes false (default)
cell_output_file_name outputfiles/cells.geojson (user set)
point_output_file_name outputfiles/points.geojson (user set)
randpts_output_file_name randPts (default)
collection_output_file_name cells (default)
shapefile_id_field_length 11 (default)
kml_default_width 4 (default)
kml_default_color ffffffff (default)
kml_name  (default)
kml_description Generated by DGGRID 7.7 (default)
neighbor_output_type TEXT (user set)
neighbor_output_file_name outputfiles/neighbors (user set)
children_output_type TEXT (user set)
children_output_file_name outputfiles/children (user set)
update_frequency 100000 (default)
max_cells_per_output_file 1000 (user set)
output_first_seqnum 1 (default)
output_last_seqnum 18446744073709551615 (default)
verbosity 0 (default)
pause_on_startup false (default)
pause_before_exit false (default)


** grid generation complete **
* generated 7,292 cells

###################################################################

**Comment by sahrk** [comment]
Sorry for the delay @ChaudhuriC . So far I'm not seeing what is happening. I've added a couple of debugging statements to the DGGRID master branch. Could you do the following?

1. Update to the latest version of `DGGRID`.
2. add the line `verbosity 3` to your meta file 
3. re-run `dggrid metafile.meta &> output.txt` and verify that your problem is still occurring
4. send me the new `output.txt`

**Comment by sahrk** [comment]
@ChaudhuriC I just updated master with a possible fix to your problem. Please download the latest version and let me know.

**Comment by ChaudhuriC** [comment]
Hi Prof. Sahr,
   We are working on updating the version. Will keep you updated on this. 

With regards,
Chiranjib

**Comment by ChaudhuriC** [comment]
Hi Prof. Sahr,
   We are working on updating the version. Will keep you updated on this. 

With regards,
Chiranjib

**Comment by Erin-1919** [comment]
Hi Dr. Sahr,

Thank you for your help! We just ran a quick test using the latest version and the generated geojson file is with valid geometries now.

This is the .meta I used:

```
dggrid_operation GENERATE_GRID

dggs_type ISEA3H
dggs_res_spec 6

clip_subset_type WHOLE_EARTH
geodetic_densify 0.0

cell_output_type GEOJSON
cell_output_file_name outputfiles/test_cell
point_output_type GEOJSON
point_output_file_name outputfiles/test_point
densification 3
precision 6
```

Erin

**Comment by sahrk** [comment]
Thanks @Erin-1919, we got lucky on that one.
