### ISSUE TITLE
Address conversions possible only from type GEO

### ISSUE THREAD

**Issue by wiktor-wiktor** [sahrk/DGGRID#76]
I try to run meta files that should perform address transform. I tried many different configurations of other parameters, but the only transformations I'm able to get are when the `input_address_type` is set to GEO. The error I'm getting is:

`DgInLocTextFile::DgInLocTextFile(): RF IDGGS11 is not longitude/latitude`

The error details of course depends on the DGG, but fail at this point regardless of the DGG set. I'm also running the examples from the project to the same effect (zTransform, z3Transform) which actually encourage changing of input/output types.

I don't think that it matters but I've built and am running on a M2 laptop.

**Comment by sahrk** [comment]
Not sure how that got broken, but I just pushed a fix to the `master` branch. I also changed the test example `z3Transform` to use non-GEO input.

**Comment by wiktor-wiktor** [comment]
Thank you, works well now!
