### ISSUE TITLE
cells.gen file is generate when running dggrid in lastest version (8.3)

### ISSUE THREAD

**Issue by tik65536** [sahrk/DGGRID#80]
Hi Kevin, 

Thanks for the latest version update on dggrid.
After I upgraded to the latest version, 8.3 of dggrid, I found an additional file (cells.gen) generated under the working directory. It is quite large in file size (>>30GB) when we generate hexagons for high resolution (resolution 14). Is this file introduced in the new version? I didn't notice this in previous versions ( or probably I missed it).

And since our wrapper will use the same working directory for the same object instance, will the file be overwritten if we call another function? Furthermore, if we involve multiple instances simultaneously with the same working dir, there is only 1 cells.gen generated, will it be a problem? 

![image](https://github.com/user-attachments/assets/568693c3-c14b-46d9-8b3b-fab0bc5f940d)

Thanks,
Tik

**Comment by sahrk** [comment]
@tik65536 by default DGGRID generates cell boundary output, with a default file name of `cells.gen`.  If you don't want cell output you must specify this in your metafile:

`cell_output_type NONE`

**Comment by tik65536** [comment]
> @tik65536 by default DGGRID generates cell boundary output, with a default file name of `cells.gen`. If you don't want cell output you must specify this in your metafile:
> 
> `cell_output_type NONE`

Thx for the checking.
Tik
