### ISSUE TITLE
[TRANSFORM_POINTS] Extra charaters are found in the generated output file (seqnum to z7string)

### ISSUE THREAD

**Issue by tik65536** [sahrk/DGGRID#83]
Hi Kevin, 

I am currently working with dggrid 8.3.4 on address transform from sequm to z7string. It is found that some times, the z7string output file will contains extra charaters after the address , for example : 
![image](https://github.com/user-attachments/assets/18ea2ef3-b070-4f1d-a7f4-46b0e31ff8c1)

And some other example : 
![image](https://github.com/user-attachments/assets/4a28579c-9f9c-4133-ab65-ff0a8c06955e)

The problem is it doesn't happen on other's, seems like it is due to env setup issue, but I couldn't locate the difference. May I ask if you may got any hits on that? 

I have attached the meta, input and output file in the gz for your reference. 
Reuploaded : 
[tmp57_z45ny.tar.gz](https://github.com/user-attachments/files/17919699/tmp57_z45ny.tar.gz)

Thanks,
Tik

**Comment by tik65536** [comment]
Some finding, 
I find that if dggrid is compiled under gcc v14 , then it works , but the extra charaters things happens under gcc12

**Comment by sahrk** [comment]
@tik65536 there was a bug in the text input code. I just updated master with a fix. Let me know if it doesn’t do the trick. The compiler version was very helpful, thanks; it allowed me to reproduce the error.

@allixender hopefully version 8.35 will now be our final version 8…
