### ISSUE TITLE
[GENERATE_GRID] The output is still in SEQNUM when the output_address_type is set to "Z7_STRING" 

### ISSUE THREAD

**Issue by tik65536** [sahrk/DGGRID#84]
Hi Kevin, 

I encountered an issue when trying to generate hexagons from an extent when the output_address_type is set to Z7_STRING.
The output cell id format is still in SEQNUM  instead of z7. Could you please help to have a check?
I have attached the metafile and clip for checking. Thanks.

Thanks,
[temp_clip_f19a52a9-6b80-4b9e-91ea-954f5e11e761.txt](https://github.com/user-attachments/files/18099219/temp_clip_f19a52a9-6b80-4b9e-91ea-954f5e11e761.txt)

[metafile_0edd6558-0f0c-4c89-a59d-cb748e380184.txt](https://github.com/user-attachments/files/18099220/metafile_0edd6558-0f0c-4c89-a59d-cb748e380184.txt)

[temp_ISEA7H_8_out_f19a52a9-6b80-4b9e-91ea-954f5e11e761.txt](https://github.com/user-attachments/files/18099235/temp_ISEA7H_8_out_f19a52a9-6b80-4b9e-91ea-954f5e11e761.txt)

Tik

**Comment by sahrk** [comment]
@tik65536  to get it to use your specified address type for output labels you have to add:

`output_cell_label_type OUTPUT_ADDRESS_TYPE`

**Comment by tik65536** [comment]
Thx @sahrk , it works.
